name: kavach_demo_pipeline
version: 1.0.0
config-version: 2

profile: kavach_demo

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  kavach_demo_pipeline:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

vars:
  start_date: "2024-01-01"
